### ISSUE TITLE
Create adapter between Orion and Elastic Search

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#52]

**Comment by CharlotteEGM** [comment]
This is in fact not possible with the current version of cygnus. The enhancement is in the pipeline. 
See this stackoverflow pipeline : http://stackoverflow.com/questions/41042084/fiware-cygnus-sink-to-elasticsearch-kibana/41180376#41180376 
But since january 2017, it is possible to pull data with http request. This is the solution I chose for the moment

**Comment by cdupont** [comment]
done: els-feeder component
